  openapi: 3.0.3
  info:
    title: Strong++
    version: 0.0.1rc0.4
    description: >-
      The Strong++ API will serve the iOS version of the app and act as a mediator
      between the server database and the client side logic and database. It
      provides access to all of the data on the server, allows for authentication
      of users and syncs offline content with the cloud.
  servers:
    - url: http://localhost:3000
  paths:
    /data/serie:
      post:
        tags:
          - "Series"
        summary: >-
          Creates a new series.
        parameters:
          - name: id_repeticiones
            in: query
            required: true
            schema:
              type: array
              items:
                type: integer
                minimum: 0
          - name: training_id
            in: query
            required: true
            schema:
              type: integer
        responses:
          '200':
              description: Operation successful
              content:
                application/json:
                  schema:
                    type: object
                    $ref: '#/components/schemas/OperationSuccessful'
          '401':
            description: Bad request
            content:
              application/json:
                schema:
                  type: object
                  $ref: '#/components/schemas/DuplicateError'
          default:
            description: Unexpected error server error
            content:
             application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ErrorModel'
    /data/repeticion:
      post:
        tags:
          - "Repeticiones"
        summary: >-
          Creates a new repetition.
        parameters:
        - name: peso
          in: query
          required: true
          schema:
            type: number
            minimum: 0
        - name:  repeticiones
          in: query
          required: true
          schema:
            type: integer
            default: 12
            format: int32
            minimum: 0      
        responses:
          '200':
              description: Operation successful
              content:
                application/json:
                  schema:
                    type: object
                    $ref: '#/components/schemas/OperationSuccessful'
          '401':
            description: Bad request
            content:
              application/json:
                schema:
                  type: object
                  $ref: '#/components/schemas/DuplicateError'
          default:
            description: Unexpected error server error
            content:
             application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ErrorModel'
    /data/repeticion/{id}:
        get:
          tags:
            - "Repeticiones"
          summary: Get repeticion
          description: >
            Descripcion
          parameters:
            - name: id
              in: path
              description: Repeticion id
              required: true
              schema:
                type: integer
                format: int32
          responses:
            '200':
              description: Return repeticion
              content:
                application/json:
                  schema:
                    type: object
                    $ref: '#/components/schemas/Repeticion'
    /data/repeticion/array:
        get:
          tags:
            - "Repeticiones"
          summary: Get repeticiones
          description: >
            Descripcion
          parameters:
            - name: id
              in: query
              description: Repeticiones id
              required: true
              schema:
                type: array
                items:
                  type: integer
                  format: int16
          responses:
            '200':
              description: Return repeticion
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: object 
                      $ref: '#/components/schemas/Repeticion'
    /data/exercises:
        get:
          tags:
            - "Ejercicios"
          summary: Get ejercicios
          description: >
            Descripcion
          responses:
            '200':
              description: Return all exercises
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: object 
                      properties:
                        id:
                          type: integer
                          format: int16
                          description: exercise Id
                          default: 16
                        name:
                          type: string
                          description: exercise name
                          default: Dumbbell curl
    /data/exercise/{id}:
      get:
          tags:
            - "Ejercicios"
          summary: Get ejercicio by id
          description: >
            Descripcion
          parameters:
            - name: id
              in: path
              required: true
              schema:
                type: integer
                format: int16
              description: Ejercicio id 
          responses:
            '200':
              description: Return exercise with that id
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: object 
                      $ref: '#/components/schemas/Exercise'

                
    /data/serie/{id}:
      get:
        tags:
          - "Series"
        summary: Get series
        description: >
          Descripcion
        parameters:
          - name: id
            in: path
            description: Series id
            required: true
            schema:
              type: integer
              format: int32
        responses:
          '200':
            description: Return series
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    $ref: '#/components/schemas/Serie'
    /data/user:
      post:
        tags:
          - "Users"
        summary: >-
          Creates a new user with the given credentials. Username should be
          unique.
        parameters:
          - name: username
            in: query
            required: true
            description: Username for the new user.
            schema:
              type: string
          - name: password
            in: query
            required: true
            description: Password for the new user.
            schema:
              type: string
        responses:
          '200':
            description: Operation successful
            content:
              application/json:
                schema:
                  type: object
                  $ref: '#/components/schemas/OperationSuccessful'
          '401':
            description: Bad request
            content:
              application/json:
                schema:
                  type: object
                  $ref: '#/components/schemas/DuplicateError'
          default:
            description: Unexpected error server error
            content:
              application/json:
                schema:
                  type: object
                  $ref: '#/components/schemas/ErrorModel'
    /data/training:
      post:
        tags:
          - "Training"
        summary: >-
          Creates a new training.

        responses:
          '200':
            description: Operation successful
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    result:
                      type: object
                      $ref: '#/components/schemas/OperationSuccessful'
                    training:
                      type: object
                      $ref: '#/components/schemas/Training'
          '401':
            description: Bad request
            content:
              application/json:
                schema:
                  type: object
                  $ref: '#/components/schemas/DuplicateError'
          default:
            description: Unexpected error server error
            content:
              application/json:
                schema:
                  type: object
                  $ref: '#/components/schemas/ErrorModel'
    /data/training/{id}:
      get:
        tags:
          - "Training"
        summary: Get training
        description: >
          Descripcion
        parameters:
          - name: id
            in: path
            description: Training id
            required: true
            schema:
              type: integer
              format: int16
        responses:
          '200':
            description: Return training
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    $ref: '#/components/schemas/Training'
    /auth/login:
      post:
        tags:
          - "Auth"
        summary: >-
          Creates a new session or returns the latest still available one.
        parameters:
          - name: username
            in: query
            required: true
            description: Username for the new user.
            schema:
              type: string
          - name: password
            in: query
            required: true
            description: Password for the new user.
            schema:
              type: string
        responses:
          '200':
            description: Operation successful
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    result:
                       type: object
                       $ref: '#/components/schemas/OperationSuccessful'
                    session:
                      type: object
                      $ref: '#/components/schemas/User_Session'
          '403':
            description: Bad request
            content:
              application/json:
                schema:
                  type: object
                  $ref: '#/components/schemas/BadCredentials'
          default:
            description: Unexpected error server error
            content:
              application/json:
                schema:
                  type: object
                  $ref: '#/components/schemas/ErrorModel'
  components:
    schemas:
      Exercise:
        type: object
        properties:
          id:
            type: integer
            format: int16
            description: Id for the exercise
            default: 3
          ex_name:
            type: string
            description: Name of the exercise
            default: "Dumbbell curl"
          ex_url:
            type: string
            description: URL for photo of the exercise
            default: "https://example.com/dumbbbellcurl.png"
      User:
        type: object
        properties:
          id:
            type: integer
            format: int16
            default: 72
            description: Id for the user
          username:
            type: string
            default: username
            description: Name of the user
          password:
            type: string
            default: hunter2
            description: Password of the user
          trainings:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  format: int16
                  default: 3
                  description: Id for the training session
                fecha:
                  type: string
                  description: Datetime of the creation of the session,
      Training:
        type: object
        properties:
          id:
            type: integer
            format: int16
            default: 4
            description: Id for the training session
          fecha:
            type: string
            description: Datetime of the creation of the sessuib,
      User_Session:
        type: object
        properties:
          id:
            type: integer
            default: 2
            description: Id for session
          token:
            type: string
            default: "ju33nq-349339n-ddfmsd7-ch7sns43-sddsg76s"
            description: Token for the session
          user_id:
            type: integer
            default: 5
            description: Owner of the token
          start_time:
            type: string
            description: start of the token validity
          timeout_s:
            type: string
            default: 7200
            description: Timeout of the token in seconds
      Repeticion:
        type: object
        properties:
          id: 
            type: integer
            format: int16
            description: Id for the exercise
            default: 6
          peso:
            type: number
            minimum: 0
          repeticiones:
            type: integer
            default: 12
            format: int32
            minimum: 0
      Serie:
        type: object
        properties:
          ejercicio:
            type: object
            description: Exercise for this series
            $ref: '#/components/schemas/Exercise'
          repeticiones:
            type: array
            items:
               type: object
               $ref: '#/components/schemas/Repeticion'
      OperationSuccessful:
        type: object
        required:
          - code
          - message
        properties:
          code:
            type: integer
            description: HTTP Status Code
            default: 200
          message:
            type: string
            default: Operation successful
            description: Operation was successful
      ErrorModel:
        type: object
        required:
          - code
          - message
        properties:
          code:
            type: integer
            description: HTTP Status Code
            minimum: 300
            maximum: 599
          error:
            type: string
            description: Message associated with that status code
      BadCredentials:
        type: object
        required:
          - code
          - message
        properties:
          code:
            type: integer
            description: HTTP Status Code
            default: 403
          error:
            type: string
            default: Bad authentication
            description:  Bad authentication
      DuplicateError:
        type: object
        required:
          - code
          - message
        properties:
          code:
            type: integer
            description: HTTP Status Code
            default: 401
          error:
            type: string
            default: Duplicate entry
            description: Duplicate entry on database.